name: XvsY
channels:
- conda-forge
- bioconda
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- _r-mutex=1.0.1
- aioeasywebdav=2.4.0
- aiohttp=3.7.3
- amply=0.1.4
- appdirs=1.4.4
- async-timeout=3.0.1
- atk=2.36.0
- atk-1.0=2.36.0
- attrs=20.3.0
- backports=1.0
- backports.functools_lru_cache=1.6.1
- bcrypt=3.2.0
- bedtools=2.29.2
- binutils_impl_linux-64=2.35.1
- binutils_linux-64=2.35
- boto3=1.16.18
- botocore=1.19.18
- brotlipy=0.7.0
- bwidget=1.9.14
- bzip2=1.0.8
- c-ares=1.11.0
- ca-certificates=2020.12.5
- cachetools=4.1.1
- cairo=1.16.0
- certifi=2020.12.5
- cffi=1.14.4
- chardet=3.0.4
- coincbc=2.10.5
- configargparse=1.2.3
- cryptography=3.2.1
- curl=7.71.1
- cycler=0.10.0
- datrie=0.8.2
- decorator=4.4.2
- docutils=0.16
- dropbox=10.4.1
- expat=2.2.10
- fftw=3.3.8
- filechunkio=1.8
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=2.001
- font-ttf-source-code-pro=2.030
- font-ttf-ubuntu=0.83
- fontconfig=2.13.1
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- freetype=2.10.4
- fribidi=1.0.10
- ftputil=4.0.0
- gcc_impl_linux-64=7.5.0
- gcc_linux-64=7.5.0
- gdk-pixbuf=2.42.0
- gettext=0.19.8.1
- gfortran_impl_linux-64=7.5.0
- gfortran_linux-64=7.5.0
- ghostscript=9.53.3
- giflib=5.2.1
- gitdb=4.0.5
- gitpython=3.1.11
- glib=2.66.2
- gobject-introspection=1.66.1
- google-api-core=1.23.0
- google-api-python-client=1.12.5
- google-auth=1.23.0
- google-auth-httplib2=0.0.4
- google-cloud-core=1.4.3
- google-cloud-storage=1.32.0
- google-crc32c=1.0.0
- google-resumable-media=1.1.0
- googleapis-common-protos=1.52.0
- graphite2=1.3.14
- graphviz=2.42.3
- gsl=2.6
- gtk2=2.24.32
- gts=0.7.6
- gxx_impl_linux-64=7.5.0
- gxx_linux-64=7.5.0
- harfbuzz=2.7.2
- httplib2=0.18.1
- icu=67.1
- idna=2.10
- imagemagick=7.0.10_28
- importlib-metadata=2.0.0
- importlib_metadata=2.0.0
- intervene=0.6.5
- ipython_genutils=0.2.0
- jbig=2.1
- jinja2=2.11.2
- jmespath=0.10.0
- jpeg=9d
- jsonschema=3.2.0
- jupyter_core=4.7.0
- kernel-headers_linux-64=2.6.32
- kiwisolver=1.3.1
- krb5=1.17.2
- lcms2=2.11
- ld_impl_linux-64=2.35.1
- libblas=3.9.0
- libcblas=3.9.0
- libcrc32c=1.1.1
- libcurl=7.71.1
- libdeflate=1.0
- libedit=3.1.20191231
- libev=4.33
- libffi=3.2.1
- libgcc-ng=9.3.0
- libgfortran-ng=7.5.0
- libgfortran4=7.5.0
- libglib=2.66.2
- libgomp=9.3.0
- libiconv=1.16
- liblapack=3.9.0
- libnghttp2=1.41.0
- libopenblas=0.3.12
- libpng=1.6.37
- libprotobuf=3.13.0.1
- librsvg=2.50.1
- libsodium=1.0.18
- libssh2=1.9.0
- libstdcxx-ng=9.3.0
- libtiff=4.1.0
- libtool=2.4.6
- libuuid=2.32.1
- libwebp=1.1.0
- libwebp-base=1.1.0
- libxcb=1.14
- libxml2=2.9.10
- lz4-c=1.9.2
- make=4.3
- markupsafe=1.1.1
- matplotlib-base=3.3.3
- multidict=4.7.5
- nbformat=5.0.8
- ncurses=6.2
- networkx=2.5
- numpy=1.19.4
- oauth2client=4.1.3
- olefile=0.46
- openjpeg=2.3.1
- openssl=1.1.1h
- pandas=1.1.4
- pango=1.42.4
- paramiko=2.7.2
- patsy=0.5.1
- pcre=8.44
- pcre2=10.35
- perl=5.26.2
- pillow=8.0.1
- pip=20.3.1
- pixman=0.38.0
- pkg-config=0.29.2
- prettytable=2.0.0
- protobuf=3.13.0.1
- psutil=5.7.3
- pulp=2.3.1
- pyasn1=0.4.8
- pyasn1-modules=0.2.8
- pybedtools=0.8.1
- pycparser=2.20
- pygments=2.7.2
- pygraphviz=1.6
- pynacl=1.4.0
- pyopenssl=19.1.0
- pyparsing=2.4.7
- pyrsistent=0.17.3
- pysam=0.15.3
- pysftp=0.2.9
- pysocks=1.7.1
- python=3.7.6
- python-dateutil=2.8.1
- python-irodsclient=0.8.2
- python_abi=3.7
- pytz=2020.4
- pyyaml=5.3.1
- r-assertthat=0.2.1
- r-backports=1.2.0
- r-base=4.0.3
- r-brio=1.1.0
- r-cairo=1.5_12.2
- r-callr=3.5.1
- r-cli=2.2.0
- r-colorspace=2.0_0
- r-corrplot=0.84
- r-crayon=1.3.4
- r-desc=1.2.0
- r-diffobj=0.3.2
- r-digest=0.6.27
- r-ellipsis=0.3.1
- r-evaluate=0.14
- r-fansi=0.4.1
- r-farver=2.0.3
- r-ggplot2=3.3.2
- r-glue=1.4.2
- r-gridextra=2.3
- r-gtable=0.3.0
- r-isoband=0.2.3
- r-jsonlite=1.7.1
- r-labeling=0.4.2
- r-lattice=0.20_41
- r-lifecycle=0.2.0
- r-magrittr=2.0.1
- r-mass=7.3_53
- r-matrix=1.2_18
- r-mgcv=1.8_33
- r-munsell=0.5.0
- r-nlme=3.1_150
- r-pillar=1.4.7
- r-pkgbuild=1.1.0
- r-pkgconfig=2.0.3
- r-pkgload=1.1.0
- r-plyr=1.8.6
- r-praise=1.0.0
- r-prettyunits=1.1.1
- r-processx=3.4.5
- r-ps=1.5.0
- r-r6=2.5.0
- r-rcolorbrewer=1.1_2
- r-rcpp=1.0.5
- r-rematch2=2.1.2
- r-rlang=0.4.9
- r-rprojroot=2.0.2
- r-rstudioapi=0.13
- r-scales=1.1.1
- r-testthat=3.0.0
- r-tibble=3.0.4
- r-upsetr=1.4.0
- r-utf8=1.1.4
- r-vctrs=0.3.5
- r-viridislite=0.3.0
- r-waldo=0.2.3
- r-withr=2.3.0
- r-zeallot=0.1.0
- ratelimiter=1.2.0
- readline=8.0
- requests=2.25.0
- rsa=4.6
- s3transfer=0.3.3
- scipy=1.5.3
- seaborn=0.11.0
- seaborn-base=0.11.0
- sed=4.8
- setuptools=49.6.0
- simplejson=3.17.2
- six=1.15.0
- slacker=0.14.0
- smmap=3.0.4
- snakemake=5.28.0
- snakemake-minimal=5.28.0
- sqlite=3.33.0
- statsmodels=0.12.1
- sysroot_linux-64=2.12
- tk=8.6.10
- tktable=2.10
- toposort=1.5
- tornado=6.1
- traitlets=5.0.5
- typing-extensions=3.7.4.3
- typing_extensions=3.7.4.3
- tzdata=2020d
- uritemplate=3.0.1
- urllib3=1.25.11
- wcwidth=0.2.5
- wheel=0.35.1
- wrapt=1.12.1
- xmlrunner=1.7.7
- xorg-kbproto=1.0.7
- xorg-libice=1.0.10
- xorg-libsm=1.2.3
- xorg-libx11=1.6.12
- xorg-libxau=1.0.9
- xorg-libxext=1.3.4
- xorg-libxpm=3.5.13
- xorg-libxrender=0.9.10
- xorg-libxt=1.1.5
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xz=5.2.5
- yaml=0.2.5
- yarl=1.5.1
- zipp=3.4.0
- zlib=1.2.11
- zstd=1.4.5